-- Query for SQL server / Azure SQL Database

SELECT cm.ACCOUNT_ID, cm.MRR AS CURRENT_MRR, lm.MRR AS LAST_MONTH_MRR FROM Table2 cm JOIN Table2 lm ON cm.ACCOUNT_ID = lm.ACCOUNT_ID
WHERE DATEPART(m, cm.MONTH)= DATEPART(m, getdate()) 
AND DATEPART(yy, lm.MONTH])= DATEPART(m, DATEADD(m, -1, getdate()))

-- Equivalent query for POSTGRES

SELECT cm.ACCOUNT_ID, cm.MRR AS CURRENT_MRR, lm.MRR AS LAST_MONTH_MRR FROM Table2 cm JOIN Table2 lm ON cm.ACCOUNT_ID = lm.ACCOUNT_ID
WHERE DATE_PART(month, cm.MONTH) = DATE_PART(month,  CURRENT_DATE)
AND DATE_PART(month, lm.MONTH) = DATE_PART(month,  CURRENT_DATE - INTERVAL '1' MONTH)
